### ISSUE TITLE
Getting the cost of a specific match?

### ISSUE THREAD

**Issue by ogencoglu** [Thinklab-SJTU/pygmtools#106]
What is the standard way to calculate the cost of a match?

**Comment by ogencoglu** [comment]
For example matching two non-isomorphic graphs (is this cost symmetric btw?)

**Comment by rogerwwww** [comment]
Hi, you may use [`pygm.utils.compute_affinity_score`](https://pygmtools.readthedocs.io/en/latest/api/_autosummary/pygmtools.utils.compute_affinity_score.html#pygmtools.utils.compute_affinity_score)
