### ISSUE TITLE
Python wget dependency

### ISSUE THREAD

**Issue by bkmgit** [Thinklab-SJTU/pygmtools#60]
Can [wget](https://pypi.org/project/wget/) be replaced with something that is being maintained or repository recreated?  Upstream repository no longer exists, though package creator @techtonik  seems to be active

**Comment by rogerwwww** [comment]
Sure. Any suggestions?

**Comment by techtonik** [comment]
I am not active at all. I did backup of Mercurial repos before Atlassian purged HG from Bitbucket. It is several GB of data. I tried to covert them down to `git`, or move them to https://sr.ht (which again requires conversion scripts) but I am getting tired really quick and can't focus, so I can't finish it for years. My brain also wants to check every line of code, and often becomes exhausted.

The only reason I open my email these days is to find some lowkey opportunities to earn some money, but there are no, so it is just an act of faith.

**Comment by techtonik** [comment]
Here is the repo backup made by good folks https://bitbucket-archive.softwareheritage.org/projects/te/techtonik/python-wget.html

If you can state what problems are you experiencing with `wget`, I can tell if they are easy to fix or not.

**Comment by bkmgit** [comment]
Thanks for the software and your other open source projects.  Python and PHP skills are in demand, Numfocus has sponsored some Python work https://numfocus.org/programs/small-development-grants . Not sure how well open source software is supported in Belarus, but have come across https://github.com/agievich/bee2

No problems with `wget`, the main issue is whether it can/will be updated as needs arise.  Can put it on sr.ht some other services are listed at https://wiki.mercurial-scm.org/MercurialHosting - can also take it over if desired, but it probably helps your profile.

**Comment by techtonik** [comment]
> https://numfocus.org/programs/small-development-grants

How much do you think I should ask to resurrect `python-wget` repo with all issues and fixed links?

> Not sure how well open source software is supported in Belarus, but have come across https://github.com/agievich/bee2

The best pay in this institution is 1000 BYN without taxes ($400) for full time, and time is my addiction. I am convinced that I am going to die in a few years (my thyroid nodule growth accelerate, psoriasis symptoms become more severe, overall fatigue is elevating as you may see from my low profile). It is very depressing to spend the rest on one's life working for basically food and shelter not being even able to understand what is happening with my body.

**Comment by bkmgit** [comment]
There is a maintained fork [pywget](https://pypi.org/project/pywget/), but it also uses [urlretrieve](https://bitbucket.org/licface/pywget/src/21bfc5e536da737c24755e7597849bb89fd24ba3/pywget/wget.py#lines-534) to download the file. wget seems to only be used in [util.py](https://github.com/Thinklab-SJTU/pygmtools/blob/main/pygmtools/utils.py#L1252) and the third option to download files also uses [urlretrieve](https://github.com/Thinklab-SJTU/pygmtools/blob/main/pygmtools/utils.py#L1257) so maybe not much is gained other than better url handling. Maybe we can try using [aiohttp](https://pypi.org/project/aiohttp/)?

**Comment by bkmgit** [comment]
> The best pay in this institution is 1000 BYN without taxes ($400) for full time, and time is my addiction.

Very dedicated people. bee2 seems like essential software.  Maybe it is better to [remove wget from pypi](https://stackoverflow.com/questions/53070421/remove-package-version-from-pypi) and indicate pywget as the successor?  As time is limited, should make best use of it. Possibly your skills can be used in another area.  Quite some use of Python in working with medical data.

**Comment by bkmgit** [comment]
@techtonik See for example https://www.python.org/jobs/7327/
