### ISSUE TITLE
about sinkhorn

### ISSUE THREAD

**Issue by lansfair** [Thinklab-SJTU/pygmtools#64]
I'm trying to use pygm.sinkhorn in my model, but it causes the gradients to vanish. Why does this happen?

**Comment by rogerwwww** [comment]
Perhaps you should try printing the output of ``pygm.sinkhorn`` -- if it is very close to 0/1 values, it may cause the issue. And try lowering the value of ``tau`` in this case.

**Comment by rogerwwww** [comment]
I am closing this issue since it seems no longer active. Plz feel free to reopen it.
