### ISSUE TITLE
About the download method for the pre-trained model

### ISSUE THREAD

**Issue by liyufeng183** [Thinklab-SJTU/pygmtools#66]
Thank you for the amazing work.Is there any domestic download method for the pre-trained model given in github?

**Comment by rogerwwww** [comment]
Thanks for your interest! You may find the baidu pan link in the documentation, for example, the [cie model here](https://pygmtools.readthedocs.io/en/latest/api/_autosummary/pygmtools.neural_solvers.cie.html#pygmtools.neural_solvers.cie:~:text=%5Bgoogle%20drive%5D%20%5Bbaidu%20drive%5D).
