### ISSUE TITLE
About the RRWM Algorithm

### ISSUE THREAD

**Issue by zjt34** [Thinklab-SJTU/pygmtools#68]
请问一下，RRWM算法中x的初始值取值有什么要求吗？是不是满足矩阵化后满秩即可？

------------------------------

May I ask, are there any requirements for the initial value of x in the RRWM algorithm? Is it enough to satisfy the full rank after matrixing?

**Comment by rogerwwww** [comment]
Hi 您好，对x的初始值没什么要求
--------------------------
Hi, there is no requirement for the initial value of x
