### ISSUE TITLE
Using import to check for existince of a package raises an error

### ISSUE THREAD

**Issue by bkmgit** [Thinklab-SJTU/pygmtools#78]
When packaging and checking if installation has occurred correctly, one tries to import pygmtools. 
The current [__init__.py](https://github.com/Thinklab-SJTU/pygmtools/blob/main/pygmtools/__init__.py)
file uses import to check for other packages. This raises an error that may prevent easy use of pygmtools
in other systems. Rather than use import, use importlib.util.find_spec as documented at
https://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it

**Comment by rogerwwww** [comment]
That makes sense. While there are other uses of "import check" in ``classic_solvers.py`` ``linear_solvers.py`` ``neural_solvers.py`` ``multi_graph_solvers.py`` and ``utils.py``, would you mind fix them together in #79 ?

You may double-check by searching for the usage of ``importlib`` in this repo.

**Comment by bkmgit** [comment]
Ok.

**Comment by rogerwwww** [comment]
Merged. Thank you!
