### ISSUE TITLE
Read and  Write graph format?

### ISSUE THREAD

**Issue by grdiv** [Thinklab-SJTU/pygmtools#90]
Can I load the graph saved by boost.graph or networkx? For example, graphml format.

**Comment by rogerwwww** [comment]
Yes you can. See this function https://pygmtools.readthedocs.io/en/latest/api/_autosummary/pygmtools.utils.build_aff_mat_from_graphml.html#pygmtools.utils.build_aff_mat_from_graphml

**Comment by grdiv** [comment]
> Yes you can. See this function https://pygmtools.readthedocs.io/en/latest/api/_autosummary/pygmtools.utils.build_aff_mat_from_graphml.html#pygmtools.utils.build_aff_mat_from_graphml

Yes, thx. I also found: https://pygmtools.readthedocs.io/en/latest/api/_autosummary/pygmtools.utils.from_graphml.html.

But I just use it, and there is an error:
pygmtools/utils.py", line 1481, in from_networkx
    adj_matrix = nx.to_numpy_matrix(G,nodelist=G.nodes()) if is_directed else nx.to_numpy_matrix(G).
So from networkx 3.0 should use to_numpy_array.

**Comment by rogerwwww** [comment]
Thanks for the update. We also have ``pygm.utils.build_aff_mat_from_networkx`` and can you please check if it accepts your data? If not, can you please provide a minimal example of the error you mentioned (also your networkX version) so that we can resolve it.

**Comment by rogerwwww** [comment]
cc @heatingma

**Comment by grdiv** [comment]
> Thanks for the update. We also have `pygm.utils.build_aff_mat_from_networkx` and can you please check if it accepts your data? If not, can you please provide a minimal example of the error you mentioned (also your networkX version) so that we can resolve it.

I just have a map.graphml file saved by boost.graph. And When I use pygmtools to deal with, It will has that error, either build_aff_mat_from_graphml() or from_graphml(). 
Because my networkx is 3.2.1,  [3.0 changelog](https://networkx.org/documentation/stable/release/release_3.0.html) has removed to_numpy_matrix.

This is a small question, I just replace to_numpy_matrix by to_numpy_array in https://github.com/Thinklab-SJTU/pygmtools/blob/5795e2b21309f6beb690df4edd5d4c8599d60bac/pygmtools/utils.py#L1481.
