### ISSUE TITLE
RRWHM algoriothm?

### ISSUE THREAD

**Issue by grdiv** [Thinklab-SJTU/pygmtools#91]
Hello，I didn't find the RRWHM[1] algorithm. Did I not find it in the document or is it in the implementation plan?
[1]Hyper-Graph Matching via Reweighted Random Walks

**Comment by rogerwwww** [comment]
Good question! We do not have any plan on that yet because the affinity tensor is kind of hard to handle, especially in a memory-efficient and scalable way.

You can find an implementation [here](https://github.com/Thinklab-SJTU/ThinkMatch/blob/master/src/qap_solvers/rrwhm.py) though

**Comment by grdiv** [comment]
ok, thank you.
