### ISSUE TITLE
connected matching nodes

### ISSUE THREAD

**Issue by smujiang** [Thinklab-SJTU/pygmtools#97]
Hi, thanks for developing this wonderful tool.
I'm working on mapping a subgraph to a whole graph. As showing in the figure, the topology/structure of the subgraph is very similar to the corresponding part of whole graph. So, the adjacent nodes in the subgraph should be mapped to the adjacent nodes in the whole graph as well. However,  by mimicing the documented example , the best result I can get likes the figure pasted here. Could you recommend the best way to solve this issue? like, what node/edge features I'd better to provide, which solver I'd better to use and parameters I need to tune? 
![image](https://github.com/Thinklab-SJTU/pygmtools/assets/23193202/0c056aee-854f-443f-a197-34fad3f450c1)

**Comment by rogerwwww** [comment]
Is the subgraph exactly the same as graph 2?

**Comment by smujiang** [comment]
> Hi Jun,
> 
> Thank you so much for using our toolkit.
> 
> Is the subgraph exactly the same as graph 2?
Hi Runzhong,
Thanks for your prompt response. 
Generally, I'm trying to use this tool for rigid image registration. Nodes in subgraph are key points from a image, Nodes in Graph 2 are key points from another image modality.  
Subgraph is not necessarily the same as graph 2. Only in some extrem cases, the nodes in subgraph have one-on-one correspondence in graph 2.  In most cases, the one-on-one correspondence is more than 90%.

**Comment by rogerwwww** [comment]
Thanks for the update. Image registration from different modalities is expected to be a challenging task, and my personal suggestion will be to try to include all the available node & edge features and tune the hyper-parameter of the affinity function (I assume you are using the Gaussian affinity function, so tune the sigma parameter)

It is also possible that traditional affinity function does not have enough capacity, and you may refer to some deep graph matching methods in this repo.

**Comment by smujiang** [comment]
Thank you so much for your recommendations. I will work on and ask if I have further questions.

**Comment by rogerwwww** [comment]
You are welcome. Feel free to reopen this issue / open another issue if there are any further questions.
